'use client';

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import {
  ShoppingCart,
  TrendingUp,
  DollarSign,
  Percent,
  Sparkles,
  HelpCircle,
  Copy,
  Check,
  ChevronRight,
  AlertTriangle,
  ShieldCheck,
  Target,
  ExternalLink,
  Flame,
  ArrowRight,
  PackageCheck,
  Zap,
  Tag
} from 'lucide-react';
import { PLATFORM_PRESETS, ECOM_NICHE_PRESETS, ECOM_AFFILIATES } from '@/data/ecommerce-data';
import { calculateEcommerceProfit } from '@/lib/ecommerce-calculator';
import { generateEcommerceAiOptimization } from '@/lib/ecommerce-ai';
import { EcommercePlatform, EcommerceInputs, AIOptimizationRecommendation } from '@/types/ecommerce';
import AdPlaceholder from '@/components/AdPlaceholder';

export default function BreakEvenRoasCalculator() {
  const [selectedPlatform, setSelectedPlatform] = useState<EcommercePlatform>('shopify');
  const [productName, setProductName] = useState<string>('Wireless Noise-Canceling Earbuds');

  // Input states
  const [sellingPrice, setSellingPrice] = useState<number>(49.99);
  const [productCogs, setProductCogs] = useState<number>(12.50);
  const [shippingCost, setShippingCost] = useState<number>(4.80);
  const [monthlyUnitsSold, setMonthlyUnitsSold] = useState<number>(450);
  const [currentAdRoas, setCurrentAdRoas] = useState<number>(2.4);

  // AI states
  const [isGeneratingAi, setIsGeneratingAi] = useState<boolean>(false);
  const [aiResult, setAiResult] = useState<AIOptimizationRecommendation | null>(null);
  const [copiedReport, setCopiedReport] = useState<boolean>(false);

  // Active platform preset
  const platformInfo = useMemo(() => {
    return PLATFORM_PRESETS.find((p) => p.id === selectedPlatform) || PLATFORM_PRESETS[0];
  }, [selectedPlatform]);

  // Main calculation
  const inputs: EcommerceInputs = useMemo(() => ({
    platform: selectedPlatform,
    sellingPrice,
    productCogs,
    shippingCost,
    processingFeePercent: platformInfo.defaultProcessingFeeRate,
    processingFeeFixed: platformInfo.defaultProcessingFixed,
    platformFeePercent: platformInfo.defaultPlatformFeeRate,
    monthlyUnitsSold,
    currentAdRoas
  }), [selectedPlatform, sellingPrice, productCogs, shippingCost, platformInfo, monthlyUnitsSold, currentAdRoas]);

  const calculation = useMemo(() => {
    return calculateEcommerceProfit(inputs);
  }, [inputs]);

  // Handle niche preset click
  const applyNichePreset = (niche: typeof ECOM_NICHE_PRESETS[0]) => {
    setProductName(niche.name);
    setSellingPrice(niche.price);
    setProductCogs(niche.cogs);
    setShippingCost(niche.shipping);
    setAiResult(null);
  };

  // Generate AI Optimization
  const handleGenerateAi = async () => {
    setIsGeneratingAi(true);
    try {
      const res = await generateEcommerceAiOptimization(inputs, calculation, productName);
      setAiResult(res);
    } finally {
      setIsGeneratingAi(false);
    }
  };

  // Copy report
  const handleCopyReport = () => {
    const text = `🛒 E-commerce Profit & ROAS Breakdown (${productName || 'Product'})
Platform: ${platformInfo.name}
Retail Price: $${sellingPrice.toFixed(2)} | COGS: $${productCogs.toFixed(2)} | Shipping: $${shippingCost.toFixed(2)}

📊 Unit Economics:
• Gross Margin: ${calculation.grossMarginPercent}% ($${calculation.grossProfitPerUnit.toFixed(2)} / unit)
• Break-Even ROAS: ${calculation.breakEvenRoas}x (Target CPA: $${calculation.breakEvenCpa.toFixed(2)})
• Target ROAS for 20% Net Margin: ${calculation.targetRoas20Percent}x
• Target ROAS for 30% Net Margin: ${calculation.targetRoas30Percent}x

💰 Monthly Forecast (${monthlyUnitsSold.toLocaleString()} units @ ${currentAdRoas}x ROAS):
• Total Revenue: $${calculation.monthlyRevenue.toLocaleString()}
• Ad Spend: $${calculation.monthlyAdSpendAtCurrentRoas.toLocaleString()}
• Net Profit: $${calculation.monthlyNetProfit.toLocaleString()} (${calculation.monthlyNetMarginPercent}% Net Margin)

Generated by ToolCalculators.com`;

    navigator.clipboard.writeText(text);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2500);
  };

  return (
    <div className="py-8 sm:py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs text-slate-500 mb-6">
          <Link href="/" className="hover:text-red-600 transition-colors">Home</Link>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <Link href="/#categories" className="hover:text-red-600 transition-colors">Finance & Business</Link>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <span className="text-slate-800 font-medium">E-commerce Profit & Break-Even ROAS Calculator</span>
        </nav>

        {/* Top Header Banner */}
        <div className="text-center max-w-3xl mx-auto mb-8 sm:mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-100 text-blue-800 text-xs font-bold uppercase tracking-wider mb-3">
            <ShoppingCart className="w-4 h-4 text-blue-600" />
            2026 Paid Ads Profitability Engine
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-slate-900 leading-tight">
            E-commerce Profit & <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600">Break-Even ROAS Calculator</span>
          </h1>
          <p className="mt-3 text-sm sm:text-base text-slate-600">
            Calculate your true break-even ad ROAS, max allowable CPA, and net profit margins across Shopify, Amazon FBA, and TikTok Shop.
          </p>
        </div>

        {/* Top AdSlot */}
        <AdPlaceholder slot="leaderboard" />

        {/* PLATFORM SELECTOR */}
        <div className="mb-6">
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
            Select Sales Channel / Platform
          </label>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
            {PLATFORM_PRESETS.map((p) => (
              <button
                key={p.id}
                type="button"
                onClick={() => {
                  setSelectedPlatform(p.id);
                  setAiResult(null);
                }}
                className={`p-3 rounded-xl border text-left transition-all ${
                  selectedPlatform === p.id
                    ? 'bg-blue-50 border-blue-500 ring-2 ring-blue-500/20 shadow-sm'
                    : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                }`}
              >
                <span className="text-xl block mb-1">{p.icon}</span>
                <span className="text-xs font-bold text-slate-900 block leading-tight">
                  {p.name}
                </span>
                <span className="text-[10px] text-slate-500 block mt-0.5">
                  Fee: {p.defaultPlatformFeeRate > 0 ? `${p.defaultPlatformFeeRate}%` : 'Standard Payment Fee'}
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* QUICK PRESETS CHIPS */}
        <div className="mb-8 flex items-center gap-2 overflow-x-auto pb-2 text-xs">
          <span className="text-slate-400 font-semibold whitespace-nowrap flex items-center gap-1">
            <Tag className="w-3.5 h-3.5" /> Quick Examples:
          </span>
          {ECOM_NICHE_PRESETS.map((niche, idx) => (
            <button
              key={idx}
              type="button"
              onClick={() => applyNichePreset(niche)}
              className="px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium whitespace-nowrap transition-colors"
            >
              {niche.name} (${niche.price})
            </button>
          ))}
        </div>

        {/* MAIN 2-COLUMN GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* LEFT COLUMN: Unit Cost Inputs (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-sm">
              <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3 mb-5">
                <DollarSign className="w-5 h-5 text-blue-600" />
                Unit Costs & Pricing
              </h2>

              {/* Product Name */}
              <div className="mb-5">
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                  Product Name / Title
                </label>
                <input
                  type="text"
                  value={productName}
                  onChange={(e) => setProductName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs sm:text-sm font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="e.g. Ergonomic Memory Foam Pillow"
                />
              </div>

              {/* 1. Retail Selling Price */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="selling-price" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Retail Selling Price
                  </label>
                  <span className="text-sm font-extrabold text-blue-700 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-100">
                    ${sellingPrice.toFixed(2)}
                  </span>
                </div>
                <input
                  id="selling-price"
                  type="range"
                  min="5"
                  max="250"
                  step="1"
                  value={sellingPrice}
                  onChange={(e) => setSellingPrice(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <div className="flex justify-between text-[11px] text-slate-400 mt-1">
                  <span>$5</span>
                  <span>$50</span>
                  <span>$120</span>
                  <span>$250+</span>
                </div>
              </div>

              {/* 2. Product Cost (COGS) */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="product-cogs" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Product Cost (COGS from Supplier)
                  </label>
                  <span className="text-sm font-bold text-slate-800">
                    ${productCogs.toFixed(2)}
                  </span>
                </div>
                <input
                  id="product-cogs"
                  type="range"
                  min="1"
                  max="120"
                  step="0.5"
                  value={productCogs}
                  onChange={(e) => setProductCogs(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
                <span className="text-[11px] text-slate-400 block mt-1">
                  What you pay the manufacturer per unit.
                </span>
              </div>

              {/* 3. Shipping & Packaging */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="shipping-cost" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Shipping & Packaging Per Order
                  </label>
                  <span className="text-sm font-bold text-slate-800">
                    ${shippingCost.toFixed(2)}
                  </span>
                </div>
                <input
                  id="shipping-cost"
                  type="range"
                  min="0"
                  max="40"
                  step="0.5"
                  value={shippingCost}
                  onChange={(e) => setShippingCost(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
              </div>

              {/* 4. Current Ad ROAS */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="current-roas" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Current / Target Ad Campaign ROAS
                  </label>
                  <span className="text-sm font-extrabold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded-md">
                    {currentAdRoas.toFixed(1)}x ROAS
                  </span>
                </div>
                <input
                  id="current-roas"
                  type="range"
                  min="0.8"
                  max="6.0"
                  step="0.1"
                  value={currentAdRoas}
                  onChange={(e) => setCurrentAdRoas(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600"
                />
                <span className="text-[11px] text-slate-400 block mt-1">
                  For every $1 spent on Meta/TikTok Ads, you generate ${currentAdRoas.toFixed(1)} in revenue.
                </span>
              </div>

              {/* 5. Monthly Volume Slider */}
              <div className="pt-3 border-t border-slate-100">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="monthly-units" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Monthly Orders Volume
                  </label>
                  <span className="text-xs font-bold text-slate-800">
                    {monthlyUnitsSold.toLocaleString()} orders/mo
                  </span>
                </div>
                <input
                  id="monthly-units"
                  type="range"
                  min="50"
                  max="5000"
                  step="50"
                  value={monthlyUnitsSold}
                  onChange={(e) => setMonthlyUnitsSold(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                />
              </div>

            </div>

            {/* Per-Unit Cost Summary Box */}
            <div className="bg-slate-900 text-white rounded-2xl p-5 shadow-sm">
              <h3 className="text-xs font-bold uppercase tracking-wider text-blue-400 mb-3 flex items-center gap-1.5">
                <PackageCheck className="w-4 h-4" />
                Unit Economics Breakdown
              </h3>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Retail Selling Price:</span>
                  <span className="font-bold text-white">${calculation.sellingPrice.toFixed(2)}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Product Supplier Cost:</span>
                  <span className="text-rose-400">-${productCogs.toFixed(2)}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Shipping & Fulfillment:</span>
                  <span className="text-rose-400">-${shippingCost.toFixed(2)}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Payment Gateway + Platform Fees:</span>
                  <span className="text-amber-400">-${(calculation.paymentGatewayFee + calculation.platformFee).toFixed(2)}</span>
                </div>
                <div className="flex justify-between py-1 text-emerald-400 font-bold text-sm">
                  <span>Gross Profit (Before Ads):</span>
                  <span>${calculation.grossProfitPerUnit.toFixed(2)}</span>
                </div>
              </div>
            </div>

          </div>

          {/* RIGHT COLUMN: Results & AI Margin Optimizer (7 cols) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Primary ROAS Highlight Box */}
            <div className="bg-white rounded-2xl border-2 border-blue-500/20 shadow-lg shadow-blue-500/5 p-6 relative overflow-hidden">
              <div className="flex items-center justify-between flex-wrap gap-2 mb-6">
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Break-Even ROAS Target
                  </span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-4xl font-black text-slate-900">
                      {calculation.breakEvenRoas}x
                    </span>
                    <span className="text-xs text-slate-500 font-medium">
                      ({Math.round(calculation.breakEvenRoas * 100)}% return required)
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 mt-1">
                    Any ad spend achieving higher than {calculation.breakEvenRoas}x is pure net profit.
                  </p>
                </div>

                <button
                  type="button"
                  onClick={handleCopyReport}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700 bg-slate-50 hover:bg-slate-100 transition-colors shadow-sm"
                >
                  {copiedReport ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-600" />
                      <span className="text-emerald-700">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-slate-500" />
                      <span>Copy Metrics</span>
                    </>
                  )}
                </button>
              </div>

              {/* 3 Metric Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5 mb-6">
                {/* Max Allowable CPA */}
                <div className="bg-blue-50/70 border border-blue-200 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-blue-800 block">
                    Break-Even CPA
                  </span>
                  <div className="mt-1 text-2xl font-black text-blue-900">
                    ${calculation.breakEvenCpa.toFixed(2)}
                  </div>
                  <span className="text-[10px] text-blue-700 mt-1 block">
                    Max ad cost to acquire 1 customer without losing money.
                  </span>
                </div>

                {/* Gross Margin */}
                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block">
                    Gross Margin %
                  </span>
                  <div className="mt-1 text-2xl font-black text-slate-900">
                    {calculation.grossMarginPercent}%
                  </div>
                  <span className="text-[10px] text-slate-500 mt-1 block">
                    Before advertising expenses.
                  </span>
                </div>

                {/* Target for 20% Net */}
                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block">
                    Target for 20% Net
                  </span>
                  <div className="mt-1 text-2xl font-black text-slate-900">
                    {calculation.targetRoas20Percent}x
                  </div>
                  <span className="text-[10px] text-slate-500 mt-1 block">
                    Target ROAS to keep 20% in pocket.
                  </span>
                </div>
              </div>

              {/* Monthly Financial Simulation */}
              <div className={`rounded-xl border p-4 transition-colors ${
                calculation.isProfitableAtCurrentRoas
                  ? 'bg-gradient-to-r from-emerald-50 to-teal-50 border-emerald-200'
                  : 'bg-gradient-to-r from-rose-50 to-red-50 border-rose-200'
              }`}>
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div>
                    <span className="text-xs font-bold uppercase tracking-wider block flex items-center gap-1.5">
                      {calculation.isProfitableAtCurrentRoas ? (
                        <ShieldCheck className="w-4 h-4 text-emerald-600" />
                      ) : (
                        <AlertTriangle className="w-4 h-4 text-rose-600" />
                      )}
                      Monthly Forecast ({monthlyUnitsSold.toLocaleString()} units @ {currentAdRoas}x ROAS)
                    </span>
                    <div className="text-xs text-slate-600 mt-1 space-x-3">
                      <span>Revenue: <strong>${calculation.monthlyRevenue.toLocaleString()}</strong></span>
                      <span>Ad Spend: <strong>${calculation.monthlyAdSpendAtCurrentRoas.toLocaleString()}</strong></span>
                    </div>
                  </div>

                  <div className="text-right">
                    <span className={`text-2xl font-black ${
                      calculation.isProfitableAtCurrentRoas ? 'text-emerald-700' : 'text-rose-600'
                    }`}>
                      {calculation.monthlyNetProfit >= 0 ? '+' : ''}${calculation.monthlyNetProfit.toLocaleString()}
                    </span>
                    <span className="block text-[10px] font-semibold text-slate-500 uppercase">
                      Net Profit ({calculation.monthlyNetMarginPercent}% Margin)
                    </span>
                  </div>
                </div>
              </div>

            </div>

            {/* AI MARGIN & AD SCALING OPTIMIZER */}
            <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-sm">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-amber-500" />
                    AI Margin & Ad Scaling Optimizer
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Diagnose unit economics and generate high-converting ad hooks + AOV bundling tactics.
                  </p>
                </div>

                <button
                  type="button"
                  onClick={handleGenerateAi}
                  disabled={isGeneratingAi}
                  className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl font-bold text-xs text-white bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 hover:from-blue-500 hover:to-indigo-500 transition-all shadow-md shadow-blue-500/20 disabled:opacity-75"
                >
                  {isGeneratingAi ? (
                    <>
                      <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      <span>Analyzing Margins...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      <span>{aiResult ? 'Regenerate Strategy' : 'Generate Scaling Strategy'}</span>
                    </>
                  )}
                </button>
              </div>

              {/* AI Output */}
              {aiResult ? (
                <div className="mt-5 space-y-5 animate-fadeIn">
                  
                  {/* Diagnosis Badge & Summary */}
                  <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
                        Margin Health Diagnosis:
                      </span>
                      <span className={`text-xs font-bold px-2 py-0.5 rounded-md ${
                        aiResult.marginHealth === 'Excellent' || aiResult.marginHealth === 'Healthy'
                          ? 'bg-emerald-100 text-emerald-800'
                          : 'bg-amber-100 text-amber-800'
                      }`}>
                        {aiResult.marginHealth}
                      </span>
                    </div>
                    <p className="text-xs text-slate-700 leading-relaxed">
                      {aiResult.summaryDiagnosis}
                    </p>
                    <p className="text-xs text-blue-700 font-semibold mt-2 border-t border-slate-200 pt-2">
                      💡 {aiResult.pricingAdvice}
                    </p>
                  </div>

                  {/* 3 AOV Tactics */}
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                      AOV (Average Order Value) Margin Boosters
                    </h4>
                    <div className="space-y-2">
                      {aiResult.aovTactics.map((tactic, idx) => (
                        <div key={idx} className="p-3 rounded-lg border border-slate-200 bg-white text-xs">
                          <div className="flex items-center justify-between gap-2 mb-1">
                            <span className="font-bold text-slate-900">{tactic.tactic}</span>
                            <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-100 whitespace-nowrap">
                              {tactic.impact}
                            </span>
                          </div>
                          <p className="text-slate-600 text-[11px] leading-relaxed">
                            {tactic.description}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* 3 High-converting Ad Hooks */}
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                      High-CTR Video Ad Hooks (TikTok / Reels / Shorts)
                    </h4>
                    <div className="space-y-2.5">
                      {aiResult.adAngleHooks.map((hook, idx) => (
                        <div key={idx} className="p-3 rounded-xl border border-indigo-100 bg-indigo-50/40 text-xs">
                          <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 block mb-1">
                            Hook #{idx + 1}: {hook.hookType}
                          </span>
                          <p className="font-mono text-xs text-slate-900 font-semibold bg-white p-2 rounded border border-slate-200">
                            {hook.script}
                          </p>
                          <span className="text-[10px] text-slate-500 block mt-1">
                            Why it works: {hook.whyItWorks}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                </div>
              ) : (
                <div className="border border-dashed border-slate-200 rounded-xl p-8 text-center bg-slate-50/50">
                  <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-500 flex items-center justify-center mx-auto mb-3">
                    <Target className="w-6 h-6" />
                  </div>
                  <h4 className="text-sm font-bold text-slate-800">
                    Get Actionable E-commerce Growth Tactics
                  </h4>
                  <p className="text-xs text-slate-500 max-w-sm mx-auto mt-1 mb-4">
                    Click the button above to receive custom AOV bundling thresholds and 3 ready-to-record video ad hooks designed to lower customer acquisition cost.
                  </p>
                  <button
                    type="button"
                    onClick={handleGenerateAi}
                    className="inline-flex items-center gap-2 px-4 py-2 text-xs font-bold text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors"
                  >
                    Analyze Product Economics
                  </button>
                </div>
              )}
            </div>

            {/* E-commerce Affiliate Offers */}
            <div className="rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50/50 via-white to-indigo-50/50 p-6 shadow-sm">
              <div className="flex items-center gap-2 mb-2">
                <span className="flex h-6 w-6 items-center justify-center rounded-md bg-blue-100 text-blue-700">
                  <ShoppingCart className="h-4 w-4" />
                </span>
                <h3 className="text-base font-bold text-slate-900">
                  Essential Software to Scale Your Store Profitably
                </h3>
              </div>
              <p className="text-xs text-slate-600 mb-5">
                Top online brands use these tools to lower ad costs and boost average customer order value:
              </p>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {ECOM_AFFILIATES.map((offer, idx) => (
                  <div
                    key={idx}
                    className="flex flex-col justify-between rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md hover:border-blue-300 transition-all group"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-2xl">{offer.icon}</span>
                        <span className="text-[10px] font-bold uppercase tracking-wider text-blue-800 bg-blue-50 px-2 py-0.5 rounded-full border border-blue-100">
                          {offer.badge}
                        </span>
                      </div>
                      <h4 className="text-sm font-bold text-slate-900 group-hover:text-blue-700 transition-colors">
                        {offer.title}
                      </h4>
                      <p className="mt-1 text-xs text-slate-600 leading-relaxed">
                        {offer.description}
                      </p>
                    </div>

                    <a
                      href={offer.link}
                      target="_blank"
                      rel="noopener noreferrer nofollow"
                      className="mt-4 inline-flex items-center justify-center gap-1.5 w-full rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white group-hover:bg-blue-600 transition-colors shadow-sm"
                    >
                      <span>{offer.ctaText}</span>
                      <ExternalLink className="h-3.5 w-3.5" />
                    </a>
                  </div>
                ))}
              </div>
            </div>

          </div>

        </div>

        {/* Bottom In-Feed Ad Banner */}
        <AdPlaceholder slot="in-feed" className="my-10" />

        {/* SEO & FAQ SECTION */}
        <section className="mt-12 pt-10 border-t border-slate-200">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-10">
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900">
                Frequently Asked Questions About Break-Even ROAS & E-commerce Margins
              </h2>
              <p className="text-sm text-slate-600 mt-2">
                Master the metrics that prevent paid ads from draining your bank account.
              </p>
            </div>

            <div className="space-y-4">
              
              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-blue-600" />
                  What is Break-Even ROAS and how is it calculated?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  <strong>Break-Even ROAS (Return On Ad Spend)</strong> is the minimum return your paid ads (Meta, TikTok, Google) must generate for you to make $0 net profit. It is calculated by dividing your <strong>Retail Selling Price</strong> by your <strong>Gross Profit per unit before ad spend</strong>. For example, if you sell an item for $50 and your gross profit is $25, your Break-Even ROAS is <code>50 / 25 = 2.00x</code>. If your ad manager reports 2.50x ROAS, you are generating 0.50x in pure net profit.
                </p>
              </div>

              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-blue-600" />
                  What is the difference between ROAS and CPA?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  <strong>ROAS</strong> is a ratio representing total revenue generated per dollar spent on ads (e.g. 3.0x = $300 revenue on $100 ad spend). 
                  <strong>CPA (Cost Per Acquisition)</strong> is the literal dollar cost to buy 1 paying customer (e.g. $22.50 per order). Your Break-Even CPA is simply your gross profit per unit—any CPA below this number means you made money on the acquisition.
                </p>
              </div>

              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-blue-600" />
                  How can I lower my Break-Even ROAS so I can scale ads faster?
                </h3>
                <div className="text-sm text-slate-600 leading-relaxed space-y-1.5">
                  <p>A lower break-even ROAS gives you an unfair advantage over competitors because you can bid higher in the ad auction. You can lower it by:</p>
                  <ul className="list-disc pl-5 space-y-1">
                    <li><strong>Increasing Average Order Value (AOV):</strong> Offering 2-pack and 3-pack quantity bundles on your product page.</li>
                    <li><strong>Implementing Post-Purchase 1-Click Upsells:</strong> Offering an add-on item immediately after checkout before the confirmation page.</li>
                    <li><strong>Negotiating Bulk Supplier COGS:</strong> Ordering 500–1,000 units instead of 100 units can cut manufacturing costs by 20%–40%.</li>
                    <li><strong>Testing a 10%–15% Price Increase:</strong> Higher ticket sizes immediately compress the required break-even multiplier.</li>
                  </ul>
                </div>
              </div>

            </div>
          </div>
        </section>

      </div>
    </div>
  );
}
