'use client';

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import {
  Briefcase,
  DollarSign,
  Calendar,
  Clock,
  Sparkles,
  HelpCircle,
  Copy,
  Check,
  ChevronRight,
  TrendingUp,
  ShieldAlert,
  FileText,
  Send,
  ExternalLink,
  Award,
  Zap,
  Info
} from 'lucide-react';
import { FREELANCE_ROLES, INVOICE_AFFILIATES } from '@/data/freelance-data';
import { calculateFreelanceRates } from '@/lib/freelance-calculator';
import { generateProjectProposal } from '@/lib/freelance-ai';
import { FreelanceRolePreset, FreelanceInputs, AIProjectProposal } from '@/types/freelance';
import AdPlaceholder from '@/components/AdPlaceholder';

export default function FreelanceRateCalculator() {
  const [selectedRole, setSelectedRole] = useState<FreelanceRolePreset>(FREELANCE_ROLES[0]);

  // Form states
  const [targetSalary, setTargetSalary] = useState<number>(FREELANCE_ROLES[0].defaultTargetSalary);
  const [monthlyExpenses, setMonthlyExpenses] = useState<number>(FREELANCE_ROLES[0].defaultMonthlyExpenses);
  const [vacationWeeks, setVacationWeeks] = useState<number>(4);
  const [hoursPerWeek, setHoursPerWeek] = useState<number>(40);
  const [billablePercentage, setBillablePercentage] = useState<number>(FREELANCE_ROLES[0].defaultBillablePercentage);
  const [taxRate, setTaxRate] = useState<number>(25);
  const [profitMarginBuffer, setProfitMarginBuffer] = useState<number>(15);

  // Proposal states
  const [projectBrief, setProjectBrief] = useState<string>(FREELANCE_ROLES[0].sampleProjectPrompt);
  const [isGeneratingProposal, setIsGeneratingProposal] = useState<boolean>(false);
  const [proposal, setProposal] = useState<AIProjectProposal | null>(null);
  const [copiedPitch, setCopiedPitch] = useState<boolean>(false);
  const [copiedSummary, setCopiedSummary] = useState<boolean>(false);

  // When user selects a new role preset
  const handleRoleChange = (role: FreelanceRolePreset) => {
    setSelectedRole(role);
    setTargetSalary(role.defaultTargetSalary);
    setMonthlyExpenses(role.defaultMonthlyExpenses);
    setBillablePercentage(role.defaultBillablePercentage);
    setProjectBrief(role.sampleProjectPrompt);
    setProposal(null);
  };

  // Perform core calculations
  const inputs: FreelanceInputs = useMemo(() => ({
    targetSalary,
    monthlyExpenses,
    vacationWeeks,
    hoursPerWeek,
    billablePercentage,
    taxRate,
    profitMarginBuffer
  }), [targetSalary, monthlyExpenses, vacationWeeks, hoursPerWeek, billablePercentage, taxRate, profitMarginBuffer]);

  const calculation = useMemo(() => {
    return calculateFreelanceRates(inputs);
  }, [inputs]);

  // Generate AI Proposal
  const handleGenerateProposal = async () => {
    if (!projectBrief.trim()) return;
    setIsGeneratingProposal(true);
    try {
      const res = await generateProjectProposal(projectBrief, selectedRole, calculation.hourlyRate.target);
      setProposal(res);
    } finally {
      setIsGeneratingProposal(false);
    }
  };

  // Copy email pitch
  const handleCopyPitch = () => {
    if (!proposal) return;
    navigator.clipboard.writeText(proposal.clientPitchEmail);
    setCopiedPitch(true);
    setTimeout(() => setCopiedPitch(false), 2500);
  };

  // Copy rate summary
  const handleCopyRateSummary = () => {
    const text = `💼 Freelance Rate Analysis (${selectedRole.name})
• Target Annual Take-Home: $${targetSalary.toLocaleString()}
• Gross Annual Target (with taxes & overhead): $${calculation.grossAnnualRevenueTarget.toLocaleString()}

💰 Recommended Freelance Rates:
• Target Hourly Rate: $${calculation.hourlyRate.target}/hr
• Day Rate (7 billable hours): $${calculation.dayRate.target}/day
• Minimum Project Floor: $${calculation.minimumProjectFloor.toLocaleString()}
• Premium / Value Rate: $${calculation.hourlyRate.premiumValue}/hr

Generated by ToolCalculators.com`;

    navigator.clipboard.writeText(text);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2500);
  };

  return (
    <div className="py-8 sm:py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs text-slate-500 mb-6">
          <Link href="/" className="hover:text-red-600 transition-colors">Home</Link>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <Link href="/#categories" className="hover:text-red-600 transition-colors">Finance & Business</Link>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <span className="text-slate-800 font-medium">Freelance Rate & Quote Generator</span>
        </nav>

        {/* Top Header Banner */}
        <div className="text-center max-w-3xl mx-auto mb-8 sm:mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold uppercase tracking-wider mb-3">
            <Briefcase className="w-4 h-4 text-emerald-600" />
            2026 Freelance Pricing Model & Proposal Generator
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-slate-900 leading-tight">
            AI Freelance Rate & <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-600">Project Quote Generator</span>
          </h1>
          <p className="mt-3 text-sm sm:text-base text-slate-600">
            Calculate your exact billable hourly and day rate with taxes and expenses included. Then generate an itemized, client-ready project proposal with 1 click.
          </p>
        </div>

        {/* Top AdSlot */}
        <AdPlaceholder slot="leaderboard" />

        {/* ROLE PRESET BUTTONS */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
              Select Your Freelance Profession (Preset Benchmarks)
            </span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5">
            {FREELANCE_ROLES.map((role) => (
              <button
                key={role.id}
                type="button"
                onClick={() => handleRoleChange(role)}
                className={`p-3 rounded-xl border text-left transition-all ${
                  selectedRole.id === role.id
                    ? 'bg-emerald-50 border-emerald-500 ring-2 ring-emerald-500/20 shadow-sm'
                    : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                }`}
              >
                <span className="text-2xl block mb-1">{role.icon}</span>
                <span className="text-xs font-bold text-slate-900 block leading-tight">
                  {role.name.split('&')[0]}
                </span>
                <span className="text-[10px] text-slate-500 font-medium block mt-1">
                  Avg: ${role.averageIndustryRate.avg}/hr
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* Main 2-Column Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* LEFT COLUMN: Inputs & Controls (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-sm">
              <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3 mb-5">
                <DollarSign className="w-5 h-5 text-emerald-600" />
                Income & Expense Breakdown
              </h2>

              {/* 1. Target Annual Salary */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="target-salary" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Desired Net Annual Take-Home
                  </label>
                  <span className="text-sm font-extrabold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-100">
                    ${targetSalary.toLocaleString()}/yr
                  </span>
                </div>
                <input
                  id="target-salary"
                  type="range"
                  min="30000"
                  max="250000"
                  step="5000"
                  value={targetSalary}
                  onChange={(e) => setTargetSalary(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
                />
                <div className="flex justify-between text-[11px] text-slate-400 mt-1">
                  <span>$30k</span>
                  <span>$80k</span>
                  <span>$150k</span>
                  <span>$250k+</span>
                </div>
              </div>

              {/* 2. Monthly Business Expenses */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="monthly-expenses" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Monthly Business Overhead
                  </label>
                  <span className="text-sm font-bold text-slate-800">
                    ${monthlyExpenses}/mo (${(monthlyExpenses * 12).toLocaleString()}/yr)
                  </span>
                </div>
                <input
                  id="monthly-expenses"
                  type="range"
                  min="50"
                  max="2500"
                  step="50"
                  value={monthlyExpenses}
                  onChange={(e) => setMonthlyExpenses(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
                />
                <span className="text-[11px] text-slate-400 block mt-1">
                  Software (Adobe, GitHub, Figma), internet, hosting, accounting, co-working.
                </span>
              </div>

              {/* 3. Estimated Taxes */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="tax-rate" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Estimated Tax & Self-Employment
                  </label>
                  <span className="text-sm font-bold text-slate-800">
                    {taxRate}%
                  </span>
                </div>
                <input
                  id="tax-rate"
                  type="range"
                  min="10"
                  max="45"
                  step="1"
                  value={taxRate}
                  onChange={(e) => setTaxRate(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
                />
                <span className="text-[11px] text-slate-400 block mt-1">
                  Freelancers must set aside 20% - 30% for federal, state, and self-employment taxes.
                </span>
              </div>

              {/* 4. Billable Hours Ratio */}
              <div className="mb-5">
                <div className="flex items-center justify-between mb-1.5">
                  <label htmlFor="billable-ratio" className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Billable Hours Ratio
                  </label>
                  <span className="text-sm font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md">
                    {billablePercentage}% Billable
                  </span>
                </div>
                <input
                  id="billable-ratio"
                  type="range"
                  min="30"
                  max="85"
                  step="5"
                  value={billablePercentage}
                  onChange={(e) => setBillablePercentage(Number(e.target.value))}
                  className="w-full h-2.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-emerald-600"
                />
                <span className="text-[11px] text-slate-500 block mt-1 leading-relaxed">
                  💡 <strong>Crucial:</strong> You cannot bill 40 hours/week. Freelancers spend 30-45% of time on emails, client calls, invoicing, and marketing.
                </span>
              </div>

              {/* 5. Vacation & Sick Weeks */}
              <div className="pt-2 border-t border-slate-100 flex items-center justify-between">
                <div>
                  <span className="text-xs font-bold text-slate-800 block">
                    Annual Time Off / Holidays
                  </span>
                  <span className="text-[11px] text-slate-500">
                    {52 - vacationWeeks} working weeks/year
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  {[2, 4, 6].map((w) => (
                    <button
                      key={w}
                      type="button"
                      onClick={() => setVacationWeeks(w)}
                      className={`text-xs font-semibold px-2.5 py-1 rounded-lg border transition-all ${
                        vacationWeeks === w
                          ? 'bg-emerald-600 text-white border-emerald-600'
                          : 'bg-slate-50 text-slate-600 border-slate-200 hover:bg-slate-100'
                      }`}
                    >
                      {w} wks
                    </button>
                  ))}
                </div>
              </div>

            </div>

            {/* Annual Financial Health Breakdown */}
            <div className="bg-slate-900 text-white rounded-2xl p-5 shadow-sm">
              <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 mb-3 flex items-center gap-1.5">
                <Info className="w-4 h-4" />
                Annual Financial Breakdown
              </h3>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Total Gross Revenue Target:</span>
                  <span className="font-bold text-white">${calculation.grossAnnualRevenueTarget.toLocaleString()}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Taxes Reserved ({taxRate}%):</span>
                  <span className="font-semibold text-rose-400">-${calculation.annualTaxAmount.toLocaleString()}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Business Overhead:</span>
                  <span className="font-semibold text-amber-400">-${calculation.annualBusinessExpenses.toLocaleString()}</span>
                </div>
                <div className="flex justify-between py-1 text-emerald-400 font-bold">
                  <span>Net Annual Take-Home:</span>
                  <span>${calculation.netAnnualTakeHome.toLocaleString()}</span>
                </div>
                <div className="flex justify-between pt-2 text-[11px] text-slate-400">
                  <span>Annual Billable Hours:</span>
                  <span>{calculation.billableHoursPerYear.toLocaleString()} hrs</span>
                </div>
              </div>
            </div>

          </div>

          {/* RIGHT COLUMN: Calculated Rates & AI Proposal Generator (7 cols) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Primary Rates Display Card */}
            <div className="bg-white rounded-2xl border-2 border-emerald-500/20 shadow-lg shadow-emerald-500/5 p-6 relative overflow-hidden">
              <div className="flex items-center justify-between flex-wrap gap-2 mb-6">
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Recommended Target Rate
                  </span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-4xl font-black text-slate-900">
                      ${calculation.hourlyRate.target}
                    </span>
                    <span className="text-sm font-semibold text-slate-500">
                      / billable hour
                    </span>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleCopyRateSummary}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 text-xs font-semibold text-slate-700 bg-slate-50 hover:bg-slate-100 transition-colors shadow-sm"
                >
                  {copiedSummary ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-600" />
                      <span className="text-emerald-700">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-slate-500" />
                      <span>Copy Rates</span>
                    </>
                  )}
                </button>
              </div>

              {/* 3 Rate Tiers */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5 mb-6">
                {/* Breakeven Floor */}
                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block">
                    Breakeven Floor
                  </span>
                  <div className="mt-1 text-2xl font-black text-slate-800">
                    ${Math.round(calculation.hourlyRate.breakeven)}/hr
                  </div>
                  <span className="text-[10px] text-slate-500 mt-1 block">
                    Zero profit buffer. Covers costs only.
                  </span>
                </div>

                {/* Day Rate */}
                <div className="bg-emerald-50/70 border border-emerald-200 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-800 block">
                    Full Day Rate
                  </span>
                  <div className="mt-1 text-2xl font-black text-emerald-700">
                    ${calculation.dayRate.target}
                  </div>
                  <span className="text-[10px] text-emerald-700 mt-1 block">
                    Based on 7 billable hours / day.
                  </span>
                </div>

                {/* Minimum Project Floor */}
                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 block">
                    Min Project Floor
                  </span>
                  <div className="mt-1 text-2xl font-black text-slate-800">
                    ${calculation.minimumProjectFloor.toLocaleString()}
                  </div>
                  <span className="text-[10px] text-slate-500 mt-1 block">
                    Never accept projects below this.
                  </span>
                </div>
              </div>

              {/* Value Pricing Callout */}
              <div className="rounded-xl bg-gradient-to-r from-teal-50 to-emerald-50 border border-teal-200 p-4">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div>
                    <span className="text-xs font-bold text-teal-900 uppercase tracking-wider flex items-center gap-1.5">
                      <Zap className="w-4 h-4 text-teal-600" />
                      Premium / Value-Based Rate: ${calculation.hourlyRate.premiumValue}/hr
                    </span>
                    <p className="text-xs text-teal-800 mt-0.5">
                      For rush deadlines, mission-critical projects, or direct revenue-generating deliverables.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* AI PROJECT PROPOSAL & SCOPE GENERATOR */}
            <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-sm">
              <div className="mb-4">
                <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-amber-500" />
                  AI Client Project Quote & Scope Generator
                </h3>
                <p className="text-xs text-slate-500 mt-0.5">
                  Describe what your client wants. AI estimates project hours, calculates a fixed fee, and drafts the milestone payment contract.
                </p>
              </div>

              {/* Project Brief Textarea */}
              <div className="mb-4">
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                  Client Project Description
                </label>
                <textarea
                  rows={3}
                  value={projectBrief}
                  onChange={(e) => setProjectBrief(e.target.value)}
                  placeholder="e.g. Build a 5-page responsive marketing website in Next.js with contact form and Stripe checkout..."
                  className="w-full bg-slate-50 border border-slate-300 rounded-xl p-3 text-xs sm:text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition-all placeholder:text-slate-400"
                />
                <div className="flex justify-between items-center mt-2">
                  <button
                    type="button"
                    onClick={() => setProjectBrief(selectedRole.sampleProjectPrompt)}
                    className="text-[11px] font-semibold text-emerald-700 hover:text-emerald-800 hover:underline"
                  >
                    Reset to {selectedRole.name} Sample Brief
                  </button>
                  <button
                    type="button"
                    onClick={handleGenerateProposal}
                    disabled={isGeneratingProposal}
                    className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold text-white bg-gradient-to-r from-emerald-600 via-teal-600 to-slate-900 hover:from-emerald-500 hover:to-teal-500 transition-all shadow-md shadow-emerald-600/20 disabled:opacity-75"
                  >
                    {isGeneratingProposal ? (
                      <>
                        <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        <span>Estimating Scope...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-3.5 h-3.5" />
                        <span>{proposal ? 'Regenerate Quote' : 'Generate Fixed Quote'}</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Generated Proposal Result */}
              {proposal && (
                <div className="mt-6 space-y-5 animate-fadeIn">
                  
                  {/* Fixed Fee Highlight */}
                  <div className="rounded-xl border border-emerald-200 bg-emerald-50/70 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div>
                      <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-800 block">
                        Recommended Fixed Project Fee
                      </span>
                      <div className="text-3xl font-black text-emerald-800">
                        ${proposal.recommendedPrice.toLocaleString()}
                      </div>
                      <span className="text-[11px] text-emerald-700">
                        Estimated ~{proposal.estimatedHours} hours (includes 15% scope buffer)
                      </span>
                    </div>

                    <div className="text-right sm:border-l sm:border-emerald-200 sm:pl-4">
                      <span className="text-[11px] text-slate-500 block">Pricing Range</span>
                      <span className="text-sm font-bold text-slate-800">
                        ${proposal.pricingRange.min.toLocaleString()} - ${proposal.pricingRange.max.toLocaleString()}
                      </span>
                    </div>
                  </div>

                  {/* Task & Hour Breakdown */}
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                      Phase & Task Breakdown
                    </h4>
                    <div className="space-y-2">
                      {proposal.tasks.map((task, idx) => (
                        <div
                          key={idx}
                          className="flex items-center justify-between p-3 rounded-lg border border-slate-200 bg-slate-50 text-xs"
                        >
                          <div>
                            <span className="font-bold text-slate-800 block">{task.task}</span>
                            <span className="text-[11px] text-slate-500">{task.description}</span>
                          </div>
                          <span className="font-extrabold text-slate-900 bg-white px-2 py-1 rounded border border-slate-200 ml-3 whitespace-nowrap">
                            {task.hours} hrs
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* 3-Tier Payment Milestones */}
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                      Payment Milestone Schedule
                    </h4>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-xs">
                      {proposal.paymentMilestones.map((m, idx) => (
                        <div key={idx} className="p-3 rounded-xl border border-slate-200 bg-white">
                          <span className="text-[10px] font-bold uppercase text-slate-400 block">
                            {m.phase} ({m.percentage}%)
                          </span>
                          <span className="text-base font-black text-emerald-700 block my-0.5">
                            ${m.amount.toLocaleString()}
                          </span>
                          <span className="text-[10px] text-slate-500 leading-tight block">
                            {m.trigger}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Scope Guardrails (Prevents Scope Creep) */}
                  <div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4 text-xs">
                    <span className="font-bold text-amber-900 flex items-center gap-1.5 mb-1.5 uppercase text-[11px]">
                      <ShieldAlert className="w-3.5 h-3.5 text-amber-700" />
                      Scope Guardrail Clauses (Included in Pitch)
                    </span>
                    <ul className="space-y-1 text-amber-950">
                      {proposal.scopeGuardrails.map((rule, idx) => (
                        <li key={idx} className="flex items-start gap-1.5">
                          <span className="text-amber-700 font-bold">•</span>
                          <span>{rule}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Ready-to-send pitch email */}
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1">
                        <FileText className="w-3.5 h-3.5 text-slate-400" />
                        Ready-to-Send Client Pitch Email
                      </span>
                      <button
                        type="button"
                        onClick={handleCopyPitch}
                        className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700 hover:text-emerald-800"
                      >
                        {copiedPitch ? (
                          <>
                            <Check className="w-3.5 h-3.5" />
                            <span>Copied to Clipboard!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy Proposal Email</span>
                          </>
                        )}
                      </button>
                    </div>

                    <pre className="p-4 rounded-xl bg-slate-900 text-slate-200 text-xs font-mono whitespace-pre-wrap leading-relaxed overflow-x-auto border border-slate-800">
                      {proposal.clientPitchEmail}
                    </pre>
                  </div>

                </div>
              )}
            </div>

            {/* Invoicing Software Affiliate Recommendations */}
            <div className="rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50/50 via-white to-teal-50/50 p-6 shadow-sm">
              <div className="flex items-center gap-2 mb-2">
                <span className="flex h-6 w-6 items-center justify-center rounded-md bg-emerald-100 text-emerald-700">
                  <Briefcase className="h-4 w-4" />
                </span>
                <h3 className="text-base font-bold text-slate-900">
                  Recommended Invoicing & Banking Tools for Freelancers
                </h3>
              </div>
              <p className="text-xs text-slate-600 mb-5">
                Collect payments on time, protect your intellectual property, and track billable client hours automatically:
              </p>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {INVOICE_AFFILIATES.map((offer, idx) => (
                  <div
                    key={idx}
                    className="flex flex-col justify-between rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md hover:border-emerald-300 transition-all group"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-2xl">{offer.icon}</span>
                        <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-100">
                          {offer.badge}
                        </span>
                      </div>
                      <h4 className="text-sm font-bold text-slate-900 group-hover:text-emerald-700 transition-colors">
                        {offer.title}
                      </h4>
                      <p className="mt-1 text-xs text-slate-600 leading-relaxed">
                        {offer.description}
                      </p>
                    </div>

                    <a
                      href={offer.link}
                      target="_blank"
                      rel="noopener noreferrer nofollow"
                      className="mt-4 inline-flex items-center justify-center gap-1.5 w-full rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white group-hover:bg-emerald-600 transition-colors shadow-sm"
                    >
                      <span>{offer.ctaText}</span>
                      <ExternalLink className="h-3.5 w-3.5" />
                    </a>
                  </div>
                ))}
              </div>
            </div>

          </div>

        </div>

        {/* Bottom In-Feed Ad Banner */}
        <AdPlaceholder slot="in-feed" className="my-10" />

        {/* SEO & FAQ SECTION */}
        <section className="mt-12 pt-10 border-t border-slate-200">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-10">
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900">
                Frequently Asked Questions About Freelance Rates & Pricing
              </h2>
              <p className="text-sm text-slate-600 mt-2">
                Industry-tested pricing strategies to maximize your take-home pay.
              </p>
            </div>

            <div className="space-y-4">
              
              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-600" />
                  Why is my freelance rate so much higher than my previous full-time salary?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  As an employee, your employer covers health insurance, paid vacation, 401(k) matches, software licenses, computer hardware, and the employer-half of payroll taxes. As an independent contractor, you must pay all self-employment taxes (approx 15.3% in the US), fund your own health benefits, purchase all equipment, and absorb unpaid sick days. A rule of thumb is that your hourly freelance rate should be <strong>2x to 2.5x</strong> your equivalent hourly corporate wage.
                </p>
              </div>

              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-600" />
                  What is a realistic billable hours ratio?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  Most beginner freelancers mistakenly assume they can bill 40 hours per week (2,080 hours per year). In reality, full-time independent professionals average between <strong>50% and 65% billable time</strong> (20 to 26 hours/week). The remaining 35% to 50% is non-billable administrative time spent finding leads, writing proposals, invoicing, attending discovery calls, and managing finances.
                </p>
              </div>

              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-600" />
                  Should I charge an hourly rate or a fixed project fee?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  Fixed project pricing is almost always superior for experienced freelancers. When you bill hourly, the faster and more proficient you become, the less money you make for the same value delivered. Fixed pricing aligns incentives: the client gets guaranteed budget certainty, and you capture the financial upside of your speed and efficiency. Always include a 15% contingency buffer in fixed bids.
                </p>
              </div>

              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-600" />
                  How do I prevent clients from scope creep without damaging the relationship?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  Prevent scope creep before it starts by outlining exactly what is included and establishing a formal change request policy in your initial agreement. State clearly: <em>"Includes up to 2 rounds of consolidated revisions. Additional features or extra iterations will be scoped and billed at our standard rate of $X/hour."</em> When a client asks for extra work, never say no—simply say: <em>"We would love to build that for you! That falls outside Phase 1, so here is the add-on quote for Phase 2."</em>
                </p>
              </div>

            </div>
          </div>
        </section>

      </div>
    </div>
  );
}
