'use client';

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import {
  Flame,
  Activity,
  Heart,
  Utensils,
  Copy,
  Check,
  ChevronRight,
  Sparkles,
  HelpCircle,
  Dumbbell,
  Apple,
  CheckCircle2,
  Calendar,
  Layers,
  ArrowRight
} from 'lucide-react';
import { Gender, ActivityLevel, FitnessGoal, MacroSplitType, DietPreference, MacroInputs, AIMealPlanResponse } from '@/types/macro';
import { calculateMacros } from '@/lib/macro-calculator';
import { generateCustomMealPlan } from '@/lib/macro-ai';
import AdPlaceholder from '@/components/AdPlaceholder';

export default function MacroTdeeCalculator() {
  const [gender, setGender] = useState<Gender>('male');
  const [age, setAge] = useState<number>(28);
  const [weightKg, setWeightKg] = useState<number>(78);
  const [heightCm, setHeightCm] = useState<number>(178);
  const [activityLevel, setActivityLevel] = useState<ActivityLevel>('moderate');
  const [goal, setGoal] = useState<FitnessGoal>('moderate_cut');
  const [splitType, setSplitType] = useState<MacroSplitType>('high_protein');
  const [dietPreference, setDietPreference] = useState<DietPreference>('high_protein');

  // AI Meal plan state
  const [isGeneratingAi, setIsGeneratingAi] = useState<boolean>(false);
  const [aiMealPlan, setAiMealPlan] = useState<AIMealPlanResponse | null>(null);
  const [copiedPlan, setCopiedPlan] = useState<boolean>(false);

  // Main calculation
  const inputs: MacroInputs = useMemo(() => ({
    gender,
    age,
    weightKg,
    heightCm,
    activityLevel,
    goal,
    splitType,
    dietPreference
  }), [gender, age, weightKg, heightCm, activityLevel, goal, splitType, dietPreference]);

  const calculation = useMemo(() => {
    return calculateMacros(inputs);
  }, [inputs]);

  // Generate AI meal plan
  const handleGenerateMealPlan = async () => {
    setIsGeneratingAi(true);
    try {
      const res = await generateCustomMealPlan(inputs, calculation);
      setAiMealPlan(res);
    } finally {
      setIsGeneratingAi(false);
    }
  };

  // Copy meal plan
  const handleCopyMealPlan = () => {
    if (!aiMealPlan) return;
    const text = `🥗 Personalized 1-Day Meal Plan (${calculation.targetCalories} kcal)
Protein: ${calculation.proteinGrams}g | Carbs: ${calculation.carbsGrams}g | Fat: ${calculation.fatGrams}g

${aiMealPlan.meals.map(m => `🍽️ ${m.mealName}: ${m.foodTitle}
${m.description}
(${m.calories} kcal - P: ${m.protein}g, C: ${m.carbs}g, F: ${m.fat}g)`).join('\n\n')}

🛒 Grocery List:
${aiMealPlan.groceryList.map(item => `• ${item}`).join('\n')}

Generated by ToolCalculators.com`;

    navigator.clipboard.writeText(text);
    setCopiedPlan(true);
    setTimeout(() => setCopiedPlan(false), 2500);
  };

  return (
    <div className="py-8 sm:py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs text-slate-500 mb-6">
          <Link href="/" className="hover:text-red-600 transition-colors">Home</Link>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <Link href="/#categories" className="hover:text-red-600 transition-colors">Health & Lifestyle</Link>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <span className="text-slate-800 font-medium">Macro & TDEE Calorie Planner</span>
        </nav>

        {/* Top Header Banner */}
        <div className="text-center max-w-3xl mx-auto mb-8 sm:mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold uppercase tracking-wider mb-3">
            <Activity className="w-4 h-4 text-emerald-600" />
            Mifflin-St Jeor Scientific Nutrition Engine
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-slate-900 leading-tight">
            Macro & <span className="text-[var(--accent-1)]">TDEE Calorie Planner</span>
          </h1>
          <p className="mt-3 text-sm sm:text-base text-slate-600">
            Estimate your BMR, maintenance calories, and target macro splits. Then create a sample one-day meal plan from your targets.
          </p>
        </div>

        {/* Top AdSlot */}
        <AdPlaceholder slot="leaderboard" />

        {/* MAIN 2-COLUMN GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* LEFT COLUMN: Inputs & Sliders (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-sm">
              <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2 border-b border-slate-100 pb-3 mb-5">
                <Dumbbell className="w-5 h-5 text-emerald-600" />
                Physical Profile & Goals
              </h2>

              {/* 1. Gender */}
              <div className="mb-5">
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                  Biological Gender
                </label>
                <div className="grid grid-cols-2 gap-2 p-1 bg-slate-100 rounded-xl">
                  <button
                    type="button"
                    onClick={() => setGender('male')}
                    className={`py-2 text-xs font-bold rounded-lg transition-all ${
                      gender === 'male' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-600'
                    }`}
                  >
                    👨 Male
                  </button>
                  <button
                    type="button"
                    onClick={() => setGender('female')}
                    className={`py-2 text-xs font-bold rounded-lg transition-all ${
                      gender === 'female' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-600'
                    }`}
                  >
                    👩 Female
                  </button>
                </div>
              </div>

              {/* 2. Age, Weight, Height */}
              <div className="grid grid-cols-3 gap-3 mb-5 text-xs">
                <div>
                  <label className="font-bold text-slate-500 block mb-1">Age (yrs)</label>
                  <input
                    type="number"
                    min="15"
                    max="90"
                    value={age}
                    onChange={(e) => setAge(Number(e.target.value))}
                    className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 font-bold text-slate-800"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-500 block mb-1">Weight (kg)</label>
                  <input
                    type="number"
                    min="35"
                    max="200"
                    value={weightKg}
                    onChange={(e) => setWeightKg(Number(e.target.value))}
                    className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 font-bold text-slate-800"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-500 block mb-1">Height (cm)</label>
                  <input
                    type="number"
                    min="120"
                    max="230"
                    value={heightCm}
                    onChange={(e) => setHeightCm(Number(e.target.value))}
                    className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 font-bold text-slate-800"
                  />
                </div>
              </div>

              {/* 3. Activity Level */}
              <div className="mb-5">
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                  Daily Activity Level
                </label>
                <select
                  value={activityLevel}
                  onChange={(e) => setActivityLevel(e.target.value as ActivityLevel)}
                  className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2.5 text-xs sm:text-sm font-semibold text-slate-800"
                >
                  <option value="sedentary">🛋️ Sedentary (Desk job, little/no exercise)</option>
                  <option value="light">🚶 Light Activity (1-2 workouts/week)</option>
                  <option value="moderate">🏃 Moderate Exercise (3-5 workouts/week)</option>
                  <option value="heavy">🏋️ Heavy Exercise (6-7 workouts/week)</option>
                  <option value="athlete">⚡ Athlete / High Physical Labor</option>
                </select>
              </div>

              {/* 4. Fitness Goal */}
              <div className="mb-5">
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                  Primary Fitness Goal
                </label>
                <select
                  value={goal}
                  onChange={(e) => setGoal(e.target.value as FitnessGoal)}
                  className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2.5 text-xs sm:text-sm font-semibold text-slate-800"
                >
                  <option value="aggressive_cut">🔥 Aggressive Fat Loss (-600 kcal deficit)</option>
                  <option value="moderate_cut">📉 Moderate Fat Loss (-350 kcal deficit)</option>
                  <option value="maintain">⚖️ Maintain Weight (Eat at TDEE)</option>
                  <option value="lean_bulk">💪 Lean Muscle Gain (+250 kcal surplus)</option>
                  <option value="heavy_bulk">🚀 Heavy Bulk (+500 kcal surplus)</option>
                </select>
              </div>

              {/* 5. Macro Split Style */}
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                  Macronutrient Ratio Preset
                </label>
                <div className="grid grid-cols-2 gap-2 text-xs">
                  {[
                    { id: 'high_protein', name: 'High Protein', desc: '40P / 35C / 25F' },
                    { id: 'balanced', name: 'Balanced', desc: '30P / 40C / 30F' },
                    { id: 'keto', name: 'Keto / Low-Carb', desc: '25P / 8C / 67F' },
                    { id: 'plant_based', name: 'Plant-Based', desc: '25P / 55C / 20F' }
                  ].map((s) => (
                    <button
                      key={s.id}
                      type="button"
                      onClick={() => setSplitType(s.id as MacroSplitType)}
                      className={`p-2.5 rounded-xl border text-left transition-all ${
                        splitType === s.id
                          ? 'bg-emerald-50 border-emerald-500 ring-2 ring-emerald-500/20 font-bold text-slate-900'
                          : 'bg-white border-slate-200 text-slate-600 hover:bg-slate-50'
                      }`}
                    >
                      <span className="block">{s.name}</span>
                      <span className="text-[10px] text-slate-400 font-normal">{s.desc}</span>
                    </button>
                  ))}
                </div>
              </div>

            </div>

            {/* BMR & TDEE Callout Card */}
            <div className="bg-slate-900 text-white rounded-2xl p-5 shadow-sm">
              <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-400 mb-3 flex items-center gap-1.5">
                <Flame className="w-4 h-4" />
                Energy Expenditure Fundamentals
              </h3>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Basal Metabolic Rate (BMR):</span>
                  <span className="font-bold text-white">{calculation.bmr.toLocaleString()} kcal/day</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-800">
                  <span className="text-slate-400">Maintenance Calories (TDEE):</span>
                  <span className="font-bold text-amber-400">{calculation.tdee.toLocaleString()} kcal/day</span>
                </div>
                <div className="flex justify-between py-1 text-emerald-400 font-bold text-sm">
                  <span>Target Daily Intake:</span>
                  <span>{calculation.targetCalories.toLocaleString()} kcal/day</span>
                </div>
              </div>
            </div>

          </div>

          {/* RIGHT COLUMN: Macro Grams & AI Meal Plan Generator (7 cols) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Target Calories & Macro Breakdown Box */}
            <div className="bg-white rounded-2xl border-2 border-emerald-500/20 shadow-lg shadow-emerald-500/5 p-6 relative overflow-hidden">
              <div className="flex items-center justify-between flex-wrap gap-2 mb-6">
                <div>
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
                    Your Daily Calorie Target
                  </span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-4xl font-black text-slate-900">
                      {calculation.targetCalories.toLocaleString()}
                    </span>
                    <span className="text-sm font-semibold text-slate-500">
                      kcal / day
                    </span>
                  </div>
                  <span className="text-xs text-emerald-700 font-medium mt-1 block">
                    {calculation.calorieAdjustment < 0 ? `${calculation.calorieAdjustment} kcal deficit` : calculation.calorieAdjustment > 0 ? `+${calculation.calorieAdjustment} kcal surplus` : 'Maintenance (0 change)'}
                  </span>
                </div>
              </div>

              {/* 3 Macro Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5 mb-6">
                {/* Protein */}
                <div className="bg-rose-50/70 border border-rose-200 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-rose-800 block">
                    Protein ({calculation.proteinPercent}%)
                  </span>
                  <div className="mt-1 text-2xl font-black text-rose-700">
                    {calculation.proteinGrams}g
                  </div>
                  <span className="text-[10px] text-rose-700 mt-1 block">
                    {calculation.proteinCalories} kcal ({((calculation.proteinGrams / weightKg)).toFixed(1)}g per kg bodyweight)
                  </span>
                </div>

                {/* Carbs */}
                <div className="bg-amber-50/70 border border-amber-200 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-amber-800 block">
                    Carbs ({calculation.carbsPercent}%)
                  </span>
                  <div className="mt-1 text-2xl font-black text-amber-700">
                    {calculation.carbsGrams}g
                  </div>
                  <span className="text-[10px] text-amber-700 mt-1 block">
                    {calculation.carbsCalories} kcal (Clean energy fuel)
                  </span>
                </div>

                {/* Fats */}
                <div className="bg-blue-50/70 border border-blue-200 rounded-xl p-4">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-blue-800 block">
                    Fats ({calculation.fatPercent}%)
                  </span>
                  <div className="mt-1 text-2xl font-black text-blue-700">
                    {calculation.fatGrams}g
                  </div>
                  <span className="text-[10px] text-blue-700 mt-1 block">
                    {calculation.fatCalories} kcal (Hormone support)
                  </span>
                </div>
              </div>
            </div>

            {/* AI 1-DAY CUSTOM MEAL PLAN GENERATOR */}
            <div className="bg-white rounded-2xl border border-slate-200 p-5 sm:p-6 shadow-sm">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Utensils className="w-5 h-5 text-emerald-600" />
                    AI 1-Day Custom Meal Plan Generator
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Generate exact meal options and portion sizes matching your {calculation.targetCalories} kcal target.
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  <select
                    value={dietPreference}
                    onChange={(e) => setDietPreference(e.target.value as DietPreference)}
                    className="bg-slate-50 border border-slate-300 rounded-xl px-2.5 py-2 text-xs font-semibold text-slate-800"
                  >
                    <option value="high_protein">High Protein (Standard)</option>
                    <option value="vegetarian">Vegetarian</option>
                    <option value="vegan">Vegan</option>
                    <option value="keto">Keto</option>
                  </select>

                  <button
                    type="button"
                    onClick={handleGenerateMealPlan}
                    disabled={isGeneratingAi}
                    className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold text-white bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 transition-all shadow-md shadow-emerald-500/20 disabled:opacity-75 whitespace-nowrap"
                  >
                    {isGeneratingAi ? (
                      <>
                        <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        <span>Generating...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-3.5 h-3.5" />
                        <span>{aiMealPlan ? 'Regenerate' : 'Generate Plan'}</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Meal Plan Display */}
              {aiMealPlan ? (
                <div className="mt-5 space-y-4 animate-fadeIn">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-emerald-800 uppercase tracking-wider">
                      {aiMealPlan.dietTitle}
                    </span>
                    <button
                      type="button"
                      onClick={handleCopyMealPlan}
                      className="text-xs font-semibold text-emerald-700 hover:text-emerald-800 flex items-center gap-1"
                    >
                      {copiedPlan ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copiedPlan ? 'Copied!' : 'Copy Plan & Grocery List'}</span>
                    </button>
                  </div>

                  <div className="grid grid-cols-1 gap-3">
                    {aiMealPlan.meals.map((meal, idx) => (
                      <div key={idx} className="p-3.5 rounded-xl border border-slate-200 bg-slate-50 text-xs">
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-bold text-emerald-800">{meal.mealName}: {meal.foodTitle}</span>
                          <span className="font-bold text-slate-800 bg-white px-2 py-0.5 rounded border border-slate-200">
                            {meal.calories} kcal
                          </span>
                        </div>
                        <p className="text-slate-600 text-[11px] leading-relaxed mb-2">
                          {meal.description}
                        </p>
                        <div className="flex gap-3 text-[10px] font-semibold text-slate-500">
                          <span className="text-rose-600">P: {meal.protein}g</span>
                          <span className="text-amber-600">C: {meal.carbs}g</span>
                          <span className="text-blue-600">F: {meal.fat}g</span>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Grocery List */}
                  <div className="p-4 rounded-xl bg-slate-900 text-slate-200 text-xs">
                    <h4 className="font-bold text-emerald-400 uppercase text-[11px] mb-2 flex items-center gap-1.5">
                      🛒 1-Day Grocery Checklist
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {aiMealPlan.groceryList.map((item, idx) => (
                        <span key={idx} className="px-2 py-1 rounded bg-slate-800 border border-slate-700 text-[11px]">
                          {item}
                        </span>
                      ))}
                    </div>
                  </div>

                </div>
              ) : (
                <div className="border border-dashed border-slate-200 rounded-xl p-8 text-center bg-slate-50/50">
                  <div className="w-12 h-12 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center mx-auto mb-3">
                    <Apple className="w-6 h-6" />
                  </div>
                  <h4 className="text-sm font-bold text-slate-800">
                    Generate Your Custom Macro-Matched Meal Plan
                  </h4>
                  <p className="text-xs text-slate-500 max-w-sm mx-auto mt-1 mb-4">
                    Click the button above to generate meals with exact portions tailored to your {calculation.targetCalories} kcal daily target.
                  </p>
                  <button
                    type="button"
                    onClick={handleGenerateMealPlan}
                    className="inline-flex items-center gap-2 px-4 py-2 text-xs font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-lg hover:bg-emerald-100 transition-colors"
                  >
                    Generate Free Meal Plan
                  </button>
                </div>
              )}
            </div>

          </div>

        </div>

        {/* Bottom In-Feed Ad Banner */}
        <AdPlaceholder slot="in-feed" className="my-10" />

        {/* SEO & FAQ SECTION */}
        <section className="mt-12 pt-10 border-t border-slate-200">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-10">
              <h2 className="text-2xl sm:text-3xl font-black text-slate-900">
                Frequently Asked Questions About TDEE & Macros
              </h2>
            </div>
            <div className="space-y-4">
              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-600" />
                  What is TDEE and why does it matter?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  <strong>TDEE (Total Daily Energy Expenditure)</strong> is the total number of calories your body burns in 24 hours, accounting for your Basal Metabolic Rate (BMR) plus physical activity. If you eat below your TDEE, you lose weight; if you eat above, you gain weight.
                </p>
              </div>
              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <h3 className="text-base font-bold text-slate-900 mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-600" />
                  How much protein do I actually need per day?
                </h3>
                <p className="text-sm text-slate-600 leading-relaxed">
                  Scientific literature recommends between <strong>1.6 to 2.2 grams of protein per kilogram of body weight</strong> (0.7 to 1.0 grams per pound) for individuals who perform strength training or are in a calorie deficit to protect lean muscle mass.
                </p>
              </div>
            </div>
          </div>
        </section>

      </div>
    </div>
  );
}
